{
  description = "A high-level library generated by minit";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    tereix-stdlib = {
      url = "github:ChaosTheChaotic/tereix-stdlib";
      flake = false;
    };
  };

  outputs =
    { self, nixpkgs, tereix-stdlib }:
    let
      systems = [
        "x86_64-linux"
        "aarch64-linux"
      ];
      forAllSystems = nixpkgs.lib.genAttrs systems;
    in
    {
      packages = forAllSystems (system: {
        default = nixpkgs.legacyPackages.${system}.callPackage ./package.nix {
          stdlibSrc = tereix-stdlib;
        };
      });

      devShells = forAllSystems (system: {
        default = nixpkgs.legacyPackages.${system}.mkShell {
          inputsFrom = [ self.packages.${system}.default ];
          packages = with nixpkgs.legacyPackages.${system}; [
            gdb
            clang-tools
            valgrind
						zstd
						cmocka
          ];
        };
      });
    };
}
